FROM raspbian/stretch
MAINTAINER gjeanmart

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive
ENV GIT_URL="https://github.com/opengsn/gsn.git"
ENV GIT_COMMIT="13fa9d029bfa8858519e25ca6f16e717d695bdab"
ENV GO_VERSION="1.14.2"
ENV GO_ETHEREUM_VERSION="1.9.13"


# Update and upgrade
RUN apt update && apt -y upgrade

# Install softwares
RUN apt install libudev-dev git curl python build-essential -y

RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
RUN apt install nodejs -y

RUN npm install -g yarn


# Install abigen
RUN wget https://dl.google.com/go/go${GO_VERSION}.linux-armv6l.tar.gz
RUN tar -C /usr/local -xvf go${GO_VERSION}.linux-armv6l.tar.gz
RUN chown root:root /usr/local/go
RUN chmod 755 /usr/local/go

RUN mkdir /go
ENV GOPATH="/go"
ENV PATH="/usr/local/go/bin:${GOPATH}/bin:${PATH}"

RUN git clone https://github.com/ethereum/go-ethereum.git --branch v${GO_ETHEREUM_VERSION}
WORKDIR /app/go-ethereum
RUN make
RUN make devtools


# Download sources
WORKDIR /app/
RUN git clone ${GIT_URL}
WORKDIR /app/gsn
RUN git fetch origin ${GIT_COMMIT}
RUN git reset --hard FETCH_HEAD


# Install
RUN yarn --network-timeout 100000
RUN make -C server
RUN cp build/server/bin/RelayHttpServer /app

# Run
CMD "sh" "-c" "/app/RelayHttpServer -Url ${URL} -Port ${LOCAL_PORT} -Workdir /app/data -EthereumNodeUrl ${NODE_URL} -RelayHubAddress ${RELAY_HUB} -GasPricePercent ${GAS_PRICE_PERCENT}"
