# gsn-relayer-persistencevolume.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gsn-relayer-ssd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/gsn-relayer"
---
